name: Build documentation

on:
  push:
#    branches: ["*-release"]
    tags:
      - "*"
  workflow_dispatch:

env:
  INSTANCE: Writerside/hi
  ARTIFACT: webHelpHI2-all.zip
  DOCKER_VERSION: 232.10165.1
  DOCS_NAME: open-docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: tag_name

      - uses: frabert/replace-string-action@v2
        if: steps.tag_name.outputs.tag != ''
        id: replace
        with:
          pattern: "(.*)-(.*)"
          string: "${{ steps.tag_name.outputs.tag }}"
          replace-with: '$1'

      - name: print tag_name
        if: ${{ success() }}
        run: echo tag_name ${{ steps.replace.outputs.replaced }}

      - name: Build Writerside
        if: ${{ success() }}
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq artifacts/${{ env.ARTIFACT }} -d ./docs/

      - name: add dockerignore
        if: ${{ success() }}
        run: |
          cat >>.dockerignore <<END
          .idea
          .git
          Dockerfile
          .dockerignore
          END

#      - name: add nginx conf
#        if: ${{ success() }}
#        run: |
#          cat >>${{ env.DOCS_NAME }}.conf <<END
#          server {
#            listen 80;
#            server_name localhost 127.0.0.1;
#            location /${{ env.DOCS_NAME }} {
#              alias /docs/${{ env.DOCS_NAME }};
#            }
#          }
#          END

      - name: add Dockerfile
        if: ${{ success() }}
        run: |
          cat >>Dockerfile <<END
          FROM liserlzhy/nginx-docs:latest
          EXPOSE 80
          COPY ${{ env.DOCS_NAME }}.conf /etc/nginx/conf.d/
          COPY ./Writerside/help-versions.json $ROOT/
          COPY ./docs/** $ROOT/$VERSION/
          COPY ./index.html $ROOT/
          WORKDIR $ROOT
          RUN rm latest
          RUN ln -s $VERSION latest
          END
        env:
          ROOT: /docs/${{ env.DOCS_NAME }}
          VERSION: ${{ steps.replace.outputs.replaced }}

      - name: Publish to Registry
        if: ${{ success() }}
        # https://github.com/elgohr/Publish-Docker-Github-Action
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: liserlzhy/nginx-docs:latest
#          name: ${{ secrets.DOCKER_REGISTRY }}/njf/open-docs:latest
#          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        if: ${{ success() }}
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: liserlzhy/nginx-docs:${{ steps.replace.outputs.replaced }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: executing remote ssh commands using ssh key
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.TX_SSH_HOST }}
#          username: ${{ secrets.TX_SSH_USER }}
#          key: ${{ secrets.TX_SSH_KEY }}
#          script: |
#            cd /home/server/openDocs/
#            sh docker-compose-runner.sh

          
