name: Build documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  INSTANCE: Writerside/hi
  ARTIFACT: webHelpHI2-all.zip
  DOCKER_VERSION: 232.10165.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Writerside
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq artifacts/${{ env.ARTIFACT }} -d ./docs

      - name: copy help-versions.json to docs
        run: cp ./Writerside/help-versions.json ./docs

      - name: add dockerignore
        run: |
          cat >>.dockerignore <<END
          .idea
          .git
          Dockerfile
          .dockerignore
          END

      - name: add Dockerfile
        run: |
          cat >>Dockerfile <<END
          FROM nginx:1.23.1-alpine
          EXPOSE 80
          COPY default.conf /etc/nginx/conf.d/
          COPY ./docs/** /docs/
          END

      - name: add default.conf
        run: |
          cat >>default.conf <<END
          server {
            listen 80;
            server_name localhost 127.0.0.1;
            location /open-docs/ {
              root /docs/;
            }
          }
          END
      - name: show docker config file
        run: ls


      - name: Publish to Registry
        # https://github.com/elgohr/Publish-Docker-Github-Action
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: liserlzhy/demo:latest
#          name: ${{ secrets.DOCKER_REGISTRY }}/njf/open-docs:latest
#          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: executing remote ssh commands using ssh key
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.TX_SSH_HOST }}
#          username: ${{ secrets.TX_SSH_USER }}
#          key: ${{ secrets.TX_SSH_KEY }}
#          script: |
#            cd /home/server/openDocs/
#            sh docker-compose-runner.sh

          
