name: Build documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  INSTANCE: Writerside/hi
  ARTIFACT: webHelpHI2-all.zip
  DOCKER_VERSION: 232.10165.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Writerside
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Show Info1
        run: |
          ls
          cd artifacts
          ls

      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq artifacts/${{ env.ARTIFACT }} -d dist

      - name: Show Info2
        run: ls